### ISSUE TITLE
Meet some problem when install

### ISSUE THREAD

**Issue by YangZhouDL** [HTLife/g2o-viewer-docker#1]
When I run "bash build.sh".I meet denial like this
![image](https://user-images.githubusercontent.com/92163060/159162812-bd01988d-424f-4190-b4ac-94487b21d8ba.png)
I don't know how to handle it,please help me.
And my docker version is 
![image](https://user-images.githubusercontent.com/92163060/159162866-6c84f84c-019e-4436-bacd-48ecc475de43.png)

**Comment by HTLife** [comment]
`sudo` can fix this problem
